InitMediaCarousel({
    SectionSelector: '.AwardsSection',
    TrackId: 'AwardsTrack',
    TrackCloneId: 'AwardsTrackClone',
    CarouselId: 'AwardsCarousel',
    HoverZoomId: 'AwardsHoverZoom',
    HoverZoomFrameSelector: '.MediaHoverZoomFrame',
    LightboxId: 'AwardsLightbox',
    LightboxContentId: 'AwardsLightboxContent',
    LightboxBodyClass: 'MediaLightboxActive',
    ItemClass: 'MediaGalleryItem',
    ItemFrameClass: 'MediaGalleryItemFrame',
    ItemMediaClass: 'MediaGalleryItemMedia',
    ItemMetaClass: 'MediaGalleryItemMeta',
    ItemLabelClass: 'MediaGalleryItemLabel',
    ItemTypeClass: 'MediaGalleryItemType',
    HoverZoomMediaClass: 'MediaHoverZoomMedia',
    HoverZoomCaptionClass: 'MediaHoverZoomCaption',
    LightboxMediaClass: 'MediaLightboxMedia',
    LightboxCaptionClass: 'MediaLightboxCaption',
    CarouselSpeed: 72,
    MediaAlt: 'Award and recognition',
    Assets: [
        { File: 'Assets/Recognition/2026-6-12.png', Label: 'June 2026' },
        { File: 'Assets/Recognition/2026-6-10.jpeg', Label: 'June 2026' },
        { File: 'Assets/Recognition/2025-12-09.png', Label: 'December 2025' },
        { File: 'Assets/Recognition/2024-03-09.png', Label: 'March 2024' },
        { File: 'Assets/Recognition/2024-7.jpg', Label: 'July 2024' },
        { File: 'Assets/Recognition/2023-10-09.png', Label: 'October 2023' },
        { File: 'Assets/Recognition/2023-9.png', Label: 'September 2023' },
        { File: 'Assets/Recognition/2022-12.png', Label: 'December 2022' },
        { File: 'Assets/Recognition/2022-3-10.png', Label: 'March 2022' },
        { File: 'Assets/Recognition/2022-3.png', Label: 'March 2022' },
        { File: 'Assets/Recognition/2022-3.jpg', Label: 'March 2022' },
        { File: 'Assets/Recognition/2021-3.png', Label: 'March 2021' },
        { File: 'Assets/Recognition/2020-3.png', Label: 'March 2020' },
        { File: 'Assets/Recognition/Picture1.jpg', Label: 'Recognition' },
        { File: 'Assets/Recognition/Picture2.jpg', Label: 'Recognition' },
        { File: 'Assets/Recognition/Picture3.jpg', Label: 'Recognition' },
        { File: 'Assets/Recognition/Picture4.png', Label: 'Recognition' },
        { File: 'Assets/Recognition/Picture5.jpg', Label: 'Recognition' }
    ]
});
