InitMediaCarousel({
    SectionSelector: '.TestimonialsSection',
    TrackId: 'TestimonialsTrack',
    TrackCloneId: 'TestimonialsTrackClone',
    CarouselId: 'TestimonialsCarousel',
    HoverZoomId: 'TestimonialsHoverZoom',
    HoverZoomFrameSelector: '.MediaHoverZoomFrame',
    LightboxId: 'TestimonialsLightbox',
    LightboxContentId: 'TestimonialsLightboxContent',
    LightboxBodyClass: 'MediaLightboxActive',
    ItemClass: 'MediaGalleryItem',
    ItemFrameClass: 'TestimonialsCardFrame',
    ItemMediaClass: 'TestimonialsCardMedia',
    ItemMetaClass: 'MediaGalleryItemMeta',
    ItemLabelClass: 'MediaGalleryItemLabel',
    ItemTypeClass: 'MediaGalleryItemType',
    HoverZoomMediaClass: 'MediaHoverZoomMedia',
    HoverZoomCaptionClass: 'MediaHoverZoomCaption',
    LightboxMediaClass: 'MediaLightboxMedia',
    LightboxCaptionClass: 'MediaLightboxCaption',
    CarouselSpeed: 68,
    MediaAlt: 'Client testimonial',
    ReverseDirection: true,
    GalleryVariant: 'Testimonial',
    ShowCaptions: false,
    Assets: [
        { File: 'Assets/Testimonials/Slide1.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide2.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide3.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide4.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide5.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide6.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide7.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide8.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide9.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide10.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide11.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide12.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide13.PNG', Label: '' },
        { File: 'Assets/Testimonials/Slide14.PNG', Label: '' }
    ]
});
